//! # DBus interface proxy for: `org.gtk.vfs.MonitorClient`
//!
//! This code was generated by `zbus-xmlgen` `4.0.0` from DBus introspection data.
//! Source: `org.gtk.vfs.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus2.github.io/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(interface = "org.gtk.vfs.MonitorClient", assume_defaults = true)]
trait MonitorClient {
    /// Changed method
    fn changed(
        &self,
        event_type: u32,
        mount_spec: &(
            &[u8],
            std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
        ),
        file_path: &[u8],
        other_mount_spec: &(
            &[u8],
            std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
        ),
        other_file_path: &[u8],
    ) -> zbus::Result<()>;
}
