//! # DBus interface proxy for: `org.gtk.vfs.Progress`
//!
//! This code was generated by `zbus-xmlgen` `4.0.0` from DBus introspection data.
//! Source: `org.gtk.vfs.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus2.github.io/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(interface = "org.gtk.vfs.Progress", assume_defaults = true)]
trait Progress {
    /// Progress method
    fn progress(&self, current: u64, total: u64) -> zbus::Result<()>;
}
