//! # DBus interface proxy for: `org.gtk.vfs.Spawner`
//!
//! This code was generated by `zbus-xmlgen` `4.0.0` from DBus introspection data.
//! Source: `org.gtk.vfs.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus2.github.io/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(interface = "org.gtk.vfs.Spawner", assume_defaults = true)]
trait Spawner {
    /// Spawned method
    fn spawned(&self, succeeded: bool, error_message: &str, error_code: u32) -> zbus::Result<()>;
}
